// packages/react/src/provider.ts
import { createContext, useContext } from 'react';
import { getDefaultStore } from 'ccstate';
import type { Store } from 'ccstate';

const StoreContext = createContext<Store | null>(null);

export const StoreProvider = StoreContext.Provider;

export function useStore(): Store {
  const store = useContext(StoreContext);

  if (!store) {
    return getDefaultStore();
  }

  return store;
}

// packages/solid/src/provider.ts
import { createContext, useContext } from 'solid-js';
import { getDefaultStore } from 'ccstate';
import type { Store } from 'ccstate';

const StoreContext = createContext<Store | null>(null);

export const StoreProvider = StoreContext.Provider;

export function useStore(): Store {
  const store = useContext(StoreContext);

  if (!store) {
    return getDefaultStore();
  }

  return store;
}
