// packages/react/src/useGet.ts
import { useSyncExternalStore } from 'react';
import { useStore } from './provider';
import { command } from 'ccstate';
import type { Computed, State } from 'ccstate';

export function useGet<T>(atom: State<T> | Computed<T>) {
  const store = useStore();
  return useSyncExternalStore(
    (fn) => {
      const ctrl = new AbortController();
      store.sub(atom, command(fn), { signal: ctrl.signal });
      return () => {
        ctrl.abort();
      };
    },
    () => {
      return store.get(atom);
    },
  );
}

// packages/solid/src/useGet.ts
import { useStore } from './provider';
import { command, type Computed, type State } from 'ccstate';
import { createSignal, onCleanup } from 'solid-js';

export function useGet<T>(atom: State<T> | Computed<T>) {
  const store = useStore();
  const [value, setValue] = createSignal<T>(store.get(atom));

  const unsub = store.sub(
    atom,
    command(() => {
      setValue(() => store.get(atom));
    }),
  );

  onCleanup(() => {
    unsub();
  });

  return value;
}
