// packages/solid/src/useGet.ts
import { useStore } from './provider';
import { command, type Computed, type State } from 'ccstate';
import { createSignal, onCleanup } from 'solid-js';

export function useGet<T>(atom: State<T> | Computed<T>) {
  const store = useStore();
  const [value, setValue] = createSignal<T>(store.get(atom));

  const unsub = store.sub(
    atom,
    command(() => {
      setValue(() => store.get(atom));
    }),
  );

  onCleanup(() => {
    unsub();
  });

  return value;
}

// src/react/chore/useGet.ts
import { useSyncExternalStore } from "react"
import { $effect, Computed, Value } from "../.."
import { useStore } from "./provider"

export function useGet<T>(atom: Value<T> | Computed<T>) {
    const store = useStore()
    return useSyncExternalStore(fn => {
        return store.sub(atom, $effect(fn))
    }, () => {
        return store.get(atom)
    })
}
